### ISSUE TITLE
Missing critical game mechanic

### ISSUE THREAD

**Issue by Jonahss** [pippinbarr/itisasifyouweredoingwork#1]
This game would be so much more fun if I could draw squares on the Desktop.

**Comment by pippinbarr** [comment]
You mean like a multiple-selection rectangle thing?

**Comment by Jonahss** [comment]
LoL yes.

This was mostly tongue-in-cheek ;) Great project.

**Comment by pippinbarr** [comment]
Hehehe. Yes, I totally wanted to have multiple selection rectangles and started doing the work for it, but it didn't feel vital enough to put in all the effort...

Thanks!

**Comment by GirlBossRush** [comment]
I second the motion :)

**Comment by pippinbarr** [comment]
Damnit! The issue is closed! Heh.
