### ISSUE TITLE
Game not working

### ISSUE THREAD

**Issue by willsoares** [pippinbarr/itisasifyouweredoingwork#3]
The square(ball) is moving correctly, but can't destroy the blocks.

**Comment by pippinbarr** [comment]
Hmm. So the ball hits the paddle but not the bricks? Any other context you can give me - like it didn't destroy _any_ bricks? Or it destroyed some and then stopped? Any messages in the JavaScript console in your browser?

**Comment by willsoares** [comment]
The ball hits the paddle and the bricks, but the bricks don't break.
Nop, no error messages.

**Comment by pippinbarr** [comment]
Ah interesting. It makes a sound when it hits the bricks?

And did you complete one set of bricks before this happened?

(It kind of sounds like there are two sets of bricks super-imposed on each other potentially...)

**Comment by pippinbarr** [comment]
Pending hearing about this again with more information I'm going to close this one for the moment.
