### ISSUE TITLE
Write "undefined"

### ISSUE THREAD

**Issue by jon-peel** [pippinbarr/itisasifyouweredoingwork#4]
I am getting a dialogue that asks me to _write "undefined"_
I am assuming that this is a javascript object that isn't there. If I actually type undefined, the dialogue shakes, and the console writes "INPUT INCORRECT".

There are no error messages in the console, so I am not able to give you more information on the problem, without looking through your code, which I don't want to do, at least not this very minute.

![download](https://user-images.githubusercontent.com/14907576/28360994-8174683e-6c77-11e7-8357-68855283bea3.jpg)

**Comment by pippinbarr** [comment]
Ah thanks for catching it. It was me not being used to using lodash's _.random (which uses an inclusive range) to pull a random array index. Fixed.
